sonar.projectKey=mishrole_efsrt-mype-web
sonar.organization=mishrole

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=efsrt-mype-web
sonar.projectVersion=1.0

sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=app
sonar.tests=app

sonar.test.inclusions=app/**/*.test.ts,app/**/*.test.tsx,app/**/*.spec.ts,app/**/*.spec.tsx
sonar.exclusions=build/**,coverage/**,.react-router/**,node_modules/**

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8